// <auto-generated />
namespace JS2247A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mediaItems_ActorMediaItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mediaItems_ActorMediaItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202404051445565_mediaItems_ActorMediaItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
