// <auto-generated />
namespace JS2247A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class increase_url_limit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(increase_url_limit));
        
        string IMigrationMetadata.Id
        {
            get { return "202404021933491_increase_url_limit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
