// <auto-generated />
namespace JS2247A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class showHasGenre1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(showHasGenre1));
        
        string IMigrationMetadata.Id
        {
            get { return "202404022127443_showHasGenre1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
